services:
  gateway:
    container_name: gateway-container
    build:
      context: ../gateway
      dockerfile: Dockerfile
    image: protu-ai/gateway:v1.0.0
    ports:
      - "80:80"
    depends_on:
      service-discovery:
        condition: service_started
