services:
  service-discovery:
    container_name: service-discovery-container
    build:
      context: ../service-discovery
      dockerfile: Dockerfile
    image: protu-ai/service-discovery:v1.0.0
    ports:
      - "8761:8761"
    volumes:
      - maven-repo:/root/.m2