services:
  user-service:
    container_name: user-service-container
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: protu-ai/user-service:v1.0.0
    ports:
      - "8085:8085"
    env_file:
      - ./.env
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - maven-repo:/root/.m2

  user-db:
    image: postgres:latest
    container_name: user-db-container
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  postgres-user-data:
