CREATE TYPE "enum_messages_sender_role" AS ENUM ('user', 'model');

CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL PRIMARY KEY,
    "public_id" CHAR(26) NOT NULL UNIQUE,
    "first_name" VARCHAR(50) NOT NULL,
    "last_name" VARCHAR(50) NOT NULL,
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password" VARCHAR(100) NOT NULL,
    "phone_number" VARCHAR(20) NOT NULL,
    "authorities" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "is_email_verified" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "chats" (
    "id" CHAR(26) PRIMARY KEY,
    "user_id" CHAR(26) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chats_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("public_id") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS "messages" (
    "id" CHAR(26) PRIMARY KEY,
    "chat_id" CHAR(26) NOT NULL,
    "sender_role" "enum_messages_sender_role" NOT NULL,
    "content" TEXT NOT NULL,
    "attachment_name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "messages_chat_id_fkey" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS "attachments" (
    "id" CHAR(26) PRIMARY KEY,
    "message_id" CHAR(26) NOT NULL,
    "file_path" VARCHAR(255) NOT NULL,
    "file_type" VARCHAR(255) NOT NULL,
    "uploaded_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "attachments_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS templates (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    body text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT templates_pkey PRIMARY KEY (id),
    CONSTRAINT template_unique_name UNIQUE (name)
);

INSERT INTO templates (name, subject, body) VALUES ('email-verification','Verify your email', '<!DOCTYPE html><html><head> <style> body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; } .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 12px; background-color: #ffffff; } .header { background-color: #007BFF; color: #fff; padding: 20px; text-align: center; border-radius: 12px 12px 0 0; } .header h1 { margin: 0; font-size: 24px; } .content { padding: 20px; } .otp-container { display: flex; justify-content: center; gap: 10px; margin: 20px 0; } .otp-box { width: 50px; height: 50px; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: bold; background-color: #007BFF; color: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); } .small { font-size: 0.9em; color: #777; text-align: center; } .footer { margin-top: 20px; font-size: 0.8em; color: #777; text-align: center; } .footer a { color: #007BFF; text-decoration: none; } .footer a:hover { text-decoration: underline; } </style></head><body> <div class="container"> <div class="header"> <h1>Protu</h1> </div> <div class="content"> <h2>Hi [[${username}]],</h2> <p>Welcome to <strong>Protu</strong>! To complete your registration, please use the following One-Time Password (OTP):</p> <div class="otp-container"> <div class="otp-box">[[${otp_1}]]</div> <div class="otp-box">[[${otp_2}]]</div> <div class="otp-box">[[${otp_3}]]</div> <div class="otp-box">[[${otp_4}]]</div> <div class="otp-box">[[${otp_5}]]</div> </div> <p class="small">This OTP is valid for <strong>[[${otpTtl}]] minutes</strong>. Do not share it with anyone.</p> <p>If you didn’t request this, please ignore this email or contact <a href="mailto:support@example.com">support@example.com</a>.</p> </div> <div class="footer"> <p>Best regards,<br>The Protu Support Team</p> <p><a href="#">Unsubscribe</a> | <a href="#">Privacy Policy</a></p> </div> </div></body></html>');

CREATE INDEX idx_chats_user_id ON "chats"("user_id");
CLUSTER chats USING idx_chats_user_id;

CREATE INDEX idx_messages_chat_id ON "messages"("chat_id");
CLUSTER messages USING idx_messages_chat_id;

CREATE INDEX idx_users_username ON "users"("username");
CREATE INDEX idx_users_email ON "users"("email");
CREATE INDEX idx_users_public_id ON "users"("public_id");
CREATE INDEX idx_attachments_message_id ON "attachments"("message_id");

CREATE INDEX idx_messages_chat_id_created_at ON "messages"("chat_id", "created_at" DESC);
CREATE INDEX idx_chats_user_id_created_at ON "chats"("user_id", "created_at" DESC);